---
title: "Advanced Data Programming in R - Homework 1"
author: "Syed Adnan Ali (23200562)"
format:
  pdf:
    fontsize: 1.5em
    toc: true
    toc-title: '**Table of Contents**'
    embed-resources: true
    grid:
      body-width: 700px
execute: 
  eval: true
  echo: false
---

## Introduction

The data set mtcars is an inbuilt dataset that was extracted from the **1974 *Motor Trend* US magazine**, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973--74 models). We will be using this for our Homework 1.

## Variables

The mtcars have the following variables which have the following descriptions

1.  `mpg`: Miles per gallon which is reflects the fuel efficiency
2.  `cyl`: Denoting the number of cylinders
3.  `disp`: Displacement
4.  `hp`: HP stands horsepower
5.  `drat`: Rear axle ratio
6.  `wt`: Weight (1000 lbs)
7.  `qsec`: 1/4 mile time
8.  `vs`: Engine . This is a categorical variable with values 0 and 1 for V shaped and Straight respectively
9.  `am`: This is a categorical variable with values with transmission values of 0 = automatic, 1 = manual
10. `gear`: Showing the number of forward gears
11. `carb`: Lastly number of carburetors

## Plotting Relationship Between Number of Carburetors and MPG

```{r}
# We will use ggplot for plotting
library(ggplot2)

# and then load the mtcars dataset
data(mtcars)

# since the car names to the dataset are not explicitely in the colm, we
# will declare the same
mtcars$car_name <- rownames(mtcars)

# Print few entries of the dataset
head(mtcars)

# then will proceed with creating the ggplot
plot <- ggplot(mtcars, aes(x = carb, y = mpg, color = car_name)) +
  geom_point(size = 3) +  # Plot the points
  geom_text(aes(label = car_name), vjust = -0.5, size = 3) +  # Add labels above points
  scale_color_discrete(name = "Car Name") +  # Add a legend for car names
  labs(title = "Relationship Between Number of Carburetors and MPG", x = "Number of Carburetors", y = "Miles Per Gallon (MPG)") +
  theme_minimal(base_size = 10) +  # Use a minimal theme and increase base font size
  theme(legend.position = "none")  # Remove legend


# Print the plot
print(plot)




```

## Plot Description

The plot shows the relationship between the number of carburetors and the miles per gallon (MPG) for differentcars.Every point on the plot denotes an automobile, and its location indicates the number of carburetors and the vehicle's mileage per gallon. Cars with more carburetors typically have lower MPG, which indicates that they are less fuel-efficient, as can be seen from the plot. Maserati Boras, for instance, have lower MPG than cars with one or two carburetors, such as the Fiat 128 or Toyota Corolla, which have greater MPG.
